name: Relase Game Binary
on:
  push:
    branches:
      - main




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get install libsdl2-dev libsdl2-image-dev

    - name: Build and Create Binary
      run: |
        cd game/static
        make
        cd ../..
        
        cp game/static/game ./game

    - name: Upload Binary as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-binary
        path: ./game
